#!/bin/bash

gnome-terminal -e "./server_pfs 5000" -t "Server"&
sleep 1
gnome-terminal -e "/home/helen/test_loc_1/client_pfs 5000 Chris" -t "Chris"&
gnome-terminal -e "/home/helen/test_loc_2/client_pfs 5000 Becca" -t "Becca"&
#gnome-terminal -e "./routedLS D logD.txt PA3_initialization.txt" -t "Router D"&
#gnome-terminal -e "./routedLS E logE.txt PA3_initialization.txt" -t "Router E"&
#gnome-terminal -e "./routedLS F logF.txt PA3_initialization.txt" -t "Router F"&
